# Generated by Cobra Compiler v0.1.0
# Date: Thu Jul  2 19:56:02 2026
.intel_syntax noprefix

# Function add
.text
.globl _add
_add:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rsp, rbp
    pop rbp
    ret

# Function subtract
.text
.globl _subtract
_subtract:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rsp, rbp
    pop rbp
    ret

# Function multiply
.text
.globl _multiply
_multiply:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rsp, rbp
    pop rbp
    ret

# Function divide
.text
.globl _divide
_divide:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov [rbp - 8], rdi
    mov [rbp - 16], rsi
    mov rsp, rbp
    pop rbp
    ret
    mov rax, 0
    push rax
    mov rcx, rax
    pop rax
    xor rdx, rdx
    div rcx

# Function main
.text
.globl _main
_main:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rip + .Lstr0]
    push rax
    mov rcx, rax
    pop rax
    add rax, rcx
    mov rdi, rax
    mov [rbp - 8], rdi
    call _cobra_print
    mov rdi, [rbp - 8]
    call _cobra_println
    lea rax, [rip + .Lstr1]
    push rax
    mov rcx, rax
    pop rax
    add rax, rcx
    mov rdi, rax
    mov [rbp - 8], rdi
    call _cobra_print
    mov rdi, [rbp - 8]
    call _cobra_println
    mov [rbp - 8], rdi
    call _cobra_print
    mov rdi, [rbp - 8]
    call _cobra_println
    lea rax, [rip + .Lstr2]
    push rax
    mov rdi, rax
    mov rsi, rax
    call _add
    mov rcx, rax
    pop rax
    add rax, rcx
    mov rdi, rax
    mov [rbp - 8], rdi
    call _cobra_print
    mov rdi, [rbp - 8]
    call _cobra_println
    lea rax, [rip + .Lstr3]
    push rax
    mov rdi, rax
    mov rsi, rax
    call _subtract
    mov rcx, rax
    pop rax
    add rax, rcx
    mov rdi, rax
    mov [rbp - 8], rdi
    call _cobra_print
    mov rdi, [rbp - 8]
    call _cobra_println
    lea rax, [rip + .Lstr4]
    push rax
    mov rdi, rax
    mov rsi, rax
    call _multiply
    mov rcx, rax
    pop rax
    add rax, rcx
    mov rdi, rax
    mov [rbp - 8], rdi
    call _cobra_print
    mov rdi, [rbp - 8]
    call _cobra_println
    lea rax, [rip + .Lstr5]
    push rax
    mov rdi, rax
    mov rsi, rax
    call _divide
    mov rcx, rax
    pop rax
    add rax, rcx
    mov rdi, rax
    mov [rbp - 8], rdi
    call _cobra_print
    mov rdi, [rbp - 8]
    call _cobra_println

.cstring
.Lstr0:
    .asciz "x = "
.Lstr1:
    .asciz "y = "
.Lstr2:
    .asciz "x + y = "
.Lstr3:
    .asciz "x - y = "
.Lstr4:
    .asciz "x * y = "
.Lstr5:
    .asciz "x / y = "

