# Generated by Cobra Compiler v0.1.0
# Date: Thu Jul  2 19:56:02 2026
.intel_syntax noprefix

# Function main
.text
.globl _main
_main:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rip + .Lstr0]
    push rax
    mov rcx, rax
    pop rax
    add rax, rcx
    push rax
    lea rax, [rip + .Lstr1]
    mov rcx, rax
    pop rax
    add rax, rcx
    push rax
    mov rcx, rax
    pop rax
    add rax, rcx
    push rax
    lea rax, [rip + .Lstr2]
    mov rcx, rax
    pop rax
    add rax, rcx
    mov rdi, rax
    mov [rbp - 8], rdi
    call _cobra_print
    mov rdi, [rbp - 8]
    call _cobra_println

.cstring
.Lstr0:
    .asciz "You are running "
.Lstr1:
    .asciz " v"
.Lstr2:
    .asciz ".0"

