# Generated by Cobra Compiler v0.1.0
# Date: Thu Jul  2 19:56:02 2026
.intel_syntax noprefix

# Function main
.text
.globl _main
_main:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov rsp, rbp
    pop rbp
    ret
    mov rax, 0
.L0:
    push rax
    mov rax, 5
    mov rcx, rax
    pop rax
    cmp rax, rcx
    setl al
    movzx rax, al
    cmp rax, 0
    je .L1
    mov rax, 0
.L2:
    mov rax, 0
.L4:
    jmp .L4
.L5:
    jmp .L2
.L3:
    jmp .L0
.L1:

