#include "compiler.h"
#include "lexer.h"
#include "parser.h"
#include "semantic.h"
#include "typechecker.h"
#include "codegen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

Compiler *compiler_create(void) {
    Compiler *c = calloc(1, sizeof(Compiler));
    c->source_path = NULL;
    c->output_path = NULL;
    c->source = NULL;
    c->diags = diag_list_create();
    c->optimize_level = 0;
    c->emit_ir = 0;
    c->verbose = 0;
    c->use_python = 0;
    c->use_cargo = 0;
    c->project_dir = NULL;
    c->link_flags = NULL;
    c->link_flag_count = 0;
    c->link_flag_capacity = 0;
    c->python_pkgs = NULL;
    c->python_pkg_count = 0;
    c->cargo_crates = NULL;
    c->cargo_crate_count = 0;
    return c;
}

void compiler_free(Compiler *c) {
    if (c) {
        free(c->source_path);
        free(c->output_path);
        free(c->source);
        for (int i = 0; i < c->link_flag_count; i++) free(c->link_flags[i]);
        free(c->link_flags);
        for (int i = 0; i < c->python_pkg_count; i++) free(c->python_pkgs[i]);
        free(c->python_pkgs);
        for (int i = 0; i < c->cargo_crate_count; i++) free(c->cargo_crates[i]);
        free(c->cargo_crates);
        diag_list_free(c->diags);
        free(c);
    }
}

static char *change_extension(const char *path, const char *new_ext) {
    const char *dot = strrchr(path, '.');
    size_t base_len = dot ? (size_t)(dot - path) : strlen(path);
    size_t ext_len = strlen(new_ext);
    char *result = malloc(base_len + ext_len + 1);
    strncpy(result, path, base_len);
    result[base_len] = '\0';
    strcat(result, new_ext);
    return result;
}

int compiler_compile_file(Compiler *c, const char *source_path, const char *output_path) {
    c->source_path = str_dup(source_path);
    c->source = read_file(source_path);

    if (!c->source) {
        diag_add(c->diags, DIAG_ERROR, 0, 0,
                 "Could not read source file '%s'", source_path);
        return 0;
    }

    if (!output_path) {
        c->output_path = change_extension(source_path, ".s");
    } else {
        c->output_path = str_dup(output_path);
    }

    if (c->verbose) {
        printf("Compiling: %s\n", source_path);
        printf("Output: %s\n", c->output_path);
    }

    return compiler_compile(c);
}

static void resolve_python_pkg(Compiler *c, const char *pkg) {
    if (c->verbose) printf("  Resolving: use python %s\n", pkg);
    char cmd[4096];
    snprintf(cmd, sizeof(cmd), "pip install %s --user -q 2>/dev/null", pkg);
    int r = system(cmd);
    if (r != 0) {
        snprintf(cmd, sizeof(cmd), "pip3 install %s --user -q 2>/dev/null", pkg);
        r = system(cmd);
    }
    if (r != 0 && c->verbose) {
        printf("  Warning: pip install %s failed\n", pkg);
    }
    c->python_pkgs = realloc(c->python_pkgs, sizeof(char*) * (c->python_pkg_count + 1));
    c->python_pkgs[c->python_pkg_count++] = strdup(pkg);
    c->use_python = 2;
}

static void ensure_cargo_src(const char *cargo_dir) {
    char src_dir[4096];
    snprintf(src_dir, sizeof(src_dir), "%s/src", cargo_dir);
    struct stat st;
    if (stat(src_dir, &st) != 0) {
        mkdir(src_dir, 0755);
    }
    char lib_rs[4096];
    snprintf(lib_rs, sizeof(lib_rs), "%s/src/lib.rs", cargo_dir);
    FILE *fp = fopen(lib_rs, "r");
    if (!fp) {
        fp = fopen(lib_rs, "w");
        if (fp) {
            fprintf(fp, "// Auto-generated by Cobra - add your extern \"C\" functions here\n");
            fprintf(fp, "// Wrap your Rust crate's functions with #[no_mangle] extern \"C\"\n");
            fclose(fp);
        }
    } else {
        fclose(fp);
    }
}

static void resolve_cargo_crate(Compiler *c, const char *pkg) {
    if (c->verbose) printf("  Resolving: use cargo %s\n", pkg);
    const char *cargo_dir = c->project_dir ? c->project_dir : ".";
    char toml_path[4096];
    snprintf(toml_path, sizeof(toml_path), "%s/Cargo.toml", cargo_dir);

    char bridge_name[512];
    snprintf(bridge_name, sizeof(bridge_name), "cobra_bridge_%s", pkg);

    FILE *fp = fopen(toml_path, "r");
    if (!fp) {
        FILE *f = fopen(toml_path, "w");
        if (f) {
            fprintf(f, "[package]\n");
            fprintf(f, "name = \"%s\"\n", bridge_name);
            fprintf(f, "version = \"0.1.0\"\n");
            fprintf(f, "edition = \"2021\"\n\n");
            fprintf(f, "[lib]\n");
            fprintf(f, "crate-type = [\"cdylib\"]\n\n");
            fprintf(f, "[dependencies]\n");
            fprintf(f, "%s = \"*\"\n", pkg);
            fclose(f);
        }
        ensure_cargo_src(cargo_dir);
        if (c->verbose) printf("  Created scaffolding for crate '%s' in Cargo.toml\n", pkg);
    } else {
        fclose(fp);
    }

    char cmd[4096];
    snprintf(cmd, sizeof(cmd), "cd %s && cargo build --release 2>/dev/null", cargo_dir);
    int r = system(cmd);
    if (r != 0 && c->verbose) {
        printf("  Warning: cargo build for '%s' failed (exit %d)\n", pkg, r);
    }

    c->cargo_crates = realloc(c->cargo_crates, sizeof(char*) * (c->cargo_crate_count + 1));
    c->cargo_crates[c->cargo_crate_count++] = strdup(bridge_name);
    c->use_cargo = 2;
}

int compiler_compile(Compiler *c) {
    if (!c->source) {
        diag_add(c->diags, DIAG_ERROR, 0, 0, "No source to compile");
        return 0;
    }

    if (c->verbose) printf("Phase 1/5: Lexing...\n");
    Lexer *lexer = lexer_create(c->source, c->diags);
    if (c->diags->count > 0) {
        diag_print_all(c->diags);
    }

    if (c->verbose) printf("Phase 2/5: Parsing...\n");
    Parser *parser = parser_create(lexer, c->diags);
    Node *ast = parser_parse(parser);
    if (parser->had_error || c->diags->count > 0) {
        diag_print_all(c->diags);
    }

    // Scan for use directives and resolve packages
    if (ast && ast->type == NODE_MODULE) {
        for (int i = 0; i < ast->data.module.statements.count; i++) {
            Node *stmt = ast->data.module.statements.items[i];
            if (stmt && stmt->type == NODE_USE_DECL) {
                const char *name = stmt->data.use_decl.name;
                const char *pkg = stmt->data.use_decl.package;
                if (name) {
                    if (strcmp(name, "python") == 0) {
                        if (pkg) {
                            resolve_python_pkg(c, pkg);
                        } else {
                            c->use_python = 1;
                            if (c->verbose) printf("  Detected: use python\n");
                        }
                    } else if (strcmp(name, "cargo") == 0) {
                        if (pkg) {
                            resolve_cargo_crate(c, pkg);
                        } else {
                            c->use_cargo = 1;
                            if (c->verbose) printf("  Detected: use cargo\n");
                        }
                    }
                }
            }
        }
    }

    if (c->verbose) printf("Phase 3/5: Semantic Analysis...\n");
    SemanticAnalyzer *semantic = semantic_create(c->diags);
    semantic_analyze(semantic, ast);
    if (semantic->had_error || c->diags->count > 0) {
        diag_print_all(c->diags);
    }

    if (c->verbose) printf("Phase 4/5: Type Checking...\n");
    TypeChecker *tc = tc_create(c->diags);
    tc_check(tc, ast);
    if (tc->had_error || c->diags->count > 0) {
        diag_print_all(c->diags);
    }

    if (c->verbose) printf("Phase 5/5: Code Generation...\n");
    CodeGenerator *cg = cg_create(c->diags);
    int result = cg_generate(cg, ast, c->output_path);
    if (!result || cg->had_error || c->diags->count > 0) {
        diag_print_all(c->diags);
    }

    cg_free(cg);
    tc_free(tc);
    semantic_free(semantic);
    node_free(ast);
    parser_free(parser);
    lexer_free(lexer);

    if (c->verbose && result) {
        printf("Compilation successful.\n");
    }

    return result;
}

const char **compiler_get_link_flags(Compiler *c, int *count) {
    if (c->link_flag_count > 0) {
        *count = c->link_flag_count;
        return (const char **)c->link_flags;
    }

    if (c->use_python) {
        FILE *fp = popen("python3-config --ldflags --embed 2>/dev/null || python3-config --ldflags 2>/dev/null", "r");
        if (fp) {
            char buf[4096] = {0};
            if (fgets(buf, sizeof(buf), fp)) {
                buf[strcspn(buf, "\n")] = 0;
                char *token = strtok(buf, " \t");
                while (token) {
                    if (token[0] == '-' && (token[1] == 'l' || token[1] == 'L')) {
                        if (c->link_flag_count >= c->link_flag_capacity) {
                            c->link_flag_capacity = c->link_flag_capacity ? c->link_flag_capacity * 2 : 8;
                            c->link_flags = realloc(c->link_flags, sizeof(char*) * c->link_flag_capacity);
                        }
                        c->link_flags[c->link_flag_count++] = strdup(token);
                    }
                    token = strtok(NULL, " \t");
                }
            }
            pclose(fp);
        } else {
            if (c->verbose) printf("Warning: python3-config not found\n");
            if (c->link_flag_count >= c->link_flag_capacity) {
                c->link_flag_capacity = 8;
                c->link_flags = malloc(sizeof(char*) * c->link_flag_capacity);
            }
            c->link_flags[c->link_flag_count++] = strdup("-lpython3");
        }

        // For Python packages, try to link the installed .so files
        // (found via python3 -c "import <pkg>; print(<pkg>.__file__)")
        for (int i = 0; i < c->python_pkg_count; i++) {
            char cmd[4096];
            snprintf(cmd, sizeof(cmd),
                     "python3 -c \"import %s; print(%s.__file__)\" 2>/dev/null",
                     c->python_pkgs[i], c->python_pkgs[i]);
            fp = popen(cmd, "r");
            if (fp) {
                char buf[1024] = {0};
                if (fgets(buf, sizeof(buf), fp)) {
                    buf[strcspn(buf, "\n")] = 0;
                    if (strstr(buf, ".so") || strstr(buf, ".dylib")) {
                        if (c->link_flag_count >= c->link_flag_capacity) {
                            c->link_flag_capacity = c->link_flag_capacity ? c->link_flag_capacity * 2 : 8;
                            c->link_flags = realloc(c->link_flags, sizeof(char*) * c->link_flag_capacity);
                        }
                        // Link the .so directly
                        char flag[4096];
                        // Get directory of the .so for -L
                        char *last_slash = strrchr(buf, '/');
                        if (last_slash) {
                            *last_slash = 0;
                            snprintf(flag, sizeof(flag), "-L%s", buf);
                            c->link_flags[c->link_flag_count++] = strdup(flag);
                            *last_slash = '/';
                        }
                        // Extract library name from .so path
                        char *so_name = strrchr(buf, '/');
                        if (so_name) so_name++; else so_name = buf;
                        char *libname = strdup(so_name);
                        // Strip lib prefix if present
                        if (strncmp(libname, "lib", 3) == 0) {
                            memmove(libname, libname + 3, strlen(libname) - 2);
                        }
                        // Strip .so or .dylib suffix
                        char *dot = strrchr(libname, '.');
                        if (dot) *dot = 0;
                        snprintf(flag, sizeof(flag), "-l%s", libname);
                        c->link_flags[c->link_flag_count++] = strdup(flag);
                        free(libname);
                    }
                }
                pclose(fp);
            }
        }
    }

    if (c->use_cargo) {
        const char *cargo_dir = c->project_dir ? c->project_dir : ".";

        // Build the base project Cargo.toml (no package = user-managed)
        if (c->use_cargo != 2) {
            char cmd[4096];
            snprintf(cmd, sizeof(cmd), "cd %s && cargo build --release 2>/dev/null", cargo_dir);
            int r = system(cmd);
            if (r != 0 && c->verbose) {
                printf("Warning: 'cargo build --release' failed (exit %d)\n", r);
            }
        }

        // Read crate name from Cargo.toml (base project)
        char toml_path[4096];
        snprintf(toml_path, sizeof(toml_path), "%s/Cargo.toml", cargo_dir);
        FILE *fp = fopen(toml_path, "r");
        char crate_name[256] = {0};
        if (fp) {
            char line[1024];
            while (fgets(line, sizeof(line), fp)) {
                if (strncmp(line, "name", 4) == 0) {
                    char *eq = strchr(line, '=');
                    if (eq) {
                        char *start = eq + 1;
                        while (*start == ' ' || *start == '"' || *start == '\'') start++;
                        char *end = start;
                        while (*end && *end != '"' && *end != '\'' && *end != '\n') end++;
                        int len = end - start;
                        if (len > 0 && len < 256) {
                            strncpy(crate_name, start, len);
                            crate_name[len] = 0;
                        }
                    }
                    break;
                }
            }
            fclose(fp);
        }

        if (crate_name[0]) {
            if (c->link_flag_count + 2 > c->link_flag_capacity) {
                c->link_flag_capacity = c->link_flag_capacity ? c->link_flag_capacity * 2 : 8;
                c->link_flags = realloc(c->link_flags, sizeof(char*) * c->link_flag_capacity);
            }
            char flag[4096];
            snprintf(flag, sizeof(flag), "-l%s", crate_name);
            c->link_flags[c->link_flag_count++] = strdup(flag);
            snprintf(flag, sizeof(flag), "-L%s/target/release", cargo_dir);
            c->link_flags[c->link_flag_count++] = strdup(flag);
        } else if (c->verbose) {
            printf("Warning: Cargo.toml not found in '%s'\n", cargo_dir);
        }
    }

    *count = c->link_flag_count;
    return (const char **)c->link_flags;
}
