# Generated by Cobra Compiler v0.1.0
# Date: Thu Jul  2 19:56:02 2026
.intel_syntax noprefix

# Function main
.text
.globl _main
_main:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov rsp, rbp
    pop rbp
    ret
    mov rax, 1
.L0:
    push rax
    mov rax, 15
    mov rcx, rax
    pop rax
    # unknown binary op
    push rax
    mov rax, 0
    mov rcx, rax
    pop rax
    cmp rax, rcx
    sete al
    movzx rax, al
    cmp rax, 0
    je .L2
    jmp .L3
.L2:
.L3:
    jmp .L0
.L1:

