# Generated by Cobra Compiler v0.1.0
# Date: Thu Jul  2 19:56:02 2026
.intel_syntax noprefix

# Function fibonacci_recursive
.text
.globl _fibonacci_recursive
_fibonacci_recursive:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov [rbp - 8], rdi
    mov rsp, rbp
    pop rbp
    ret
    push rax
    mov rax, 1
    mov rcx, rax
    pop rax
    sub rax, rcx
    mov rdi, rax
    call _fibonacci_recursive
    push rax
    push rax
    mov rax, 2
    mov rcx, rax
    pop rax
    sub rax, rcx
    mov rdi, rax
    call _fibonacci_recursive
    mov rcx, rax
    pop rax
    add rax, rcx

# Function fibonacci_iterative
.text
.globl _fibonacci_iterative
_fibonacci_iterative:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov [rbp - 8], rdi
    mov rsp, rbp
    pop rbp
    ret
    mov rax, 2
.L0:

# Function main
.text
.globl _main
_main:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rip + .Lstr2]
    mov rdi, rax
    mov [rbp - 8], rdi
    call _cobra_print
    mov rdi, [rbp - 8]
    call _cobra_println
    mov rax, 0
.L3:
    mov rax, 0
.L5:
    jmp .L5
.L6:
    jmp .L3
.L4:
    jmp .L0
.L1:

.cstring
.Lstr0:
    .asciz "Recursive:"

