# Generated by Cobra Compiler v0.1.0
# Date: Thu Jul  2 19:56:10 2026
.intel_syntax noprefix

# Function main
.text
.globl _main
_main:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov rsp, rbp
    pop rbp
    ret
    lea rax, [rip + .Lstr0]
    mov rdi, rax
    mov [rbp - 8], rdi
    call _cobra_print
    mov rdi, [rbp - 8]
    call _cobra_println
    lea rax, [rip + .Lstr1]
    mov rdi, rax
    mov [rbp - 8], rdi
    call _cobra_print
    mov rdi, [rbp - 8]
    call _cobra_println
.L2:
    push rax
    mov rcx, rax
    pop rax
    cmp rax, rcx
    setne al
    movzx rax, al
    cmp rax, 0
    je .L3
    push rax
    mov rcx, rax
    pop rax
    cmp rax, rcx
    setl al
    movzx rax, al
    cmp rax, 0
    je .L4
    jmp .L5
.L4:
.L5:
    jmp .L2
.L3:

.cstring
.Lstr0:
    .asciz "I'm thinking of a number between 1 and 100."
.Lstr1:
    .asciz "Can you guess it?"

